version: '3'

services:
  db:
    image: postgres:13.3
    ports:
      - '5432:5432'
    environment: 
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - drupal-data:/var/lib/postgresql/data'
  drupal:
    build:
      context: .
      dockerfile: drupal.Dockerfile
    image: custom-drupal
    ports:
      - '8080:80'
    volumes:
      - 'drupal-modules:/var/www/html/modules'
      - 'drupal-profiles:/var/www/html/profiles'
      - 'drupal-sites:/var/www/html/sites'
      - 'drupal-themes:/var/www/html/themes'
    environment: 
      - POSTGRES_DB=drupal
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=mysecretpassword
    depends_on: 
      - db
volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
  drupal-data: